cabal-version:      3.0
name:               identify
version:            0.1.0.0
license:            MIT
license-file:       LICENSE
author:             zerokqx
maintainer:         swiftkey382@gmail.com
category:           Web
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common common-all
    ghc-options: -Wall
    default-extensions:
        OverloadedStrings
        DeriveGeneric
        DerivingStrategies
        GeneralizedNewtypeDeriving
    default-language: GHC2021

library
    import:           common-all
    hs-source-dirs:   src
    exposed-modules:
        Identify.App
    build-depends:
        base ^>=4.20.2.0,
        aeson,
        scotty,
        text,
        bytestring,
        time,
        http-types

executable identify
    import:           common-all
    main-is:          Main.hs
    hs-source-dirs:   app
    ghc-options:      -threaded
    build-depends:
        base ^>=4.20.2.0,
        identify
