/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Upward Uptime Service API
 * REST API сервиса мониторинга доступности сайтов (uptime) в монорепозитории Upward.
 *
 * ### Возможности сервиса:
 * - Регистрация сайтов для периодического мониторинга доступности
 * - Защита от SSRF (DNS-резолвинг, фильтрация приватных/локальных сетей и проверка по списку запрещённых IP)
 * - Фоновый параллельный опрос сайтов с записью метрик в TimescaleDB
 * - Получение списка отслеживаемых сайтов и метаданных последних проверок
 * - Проверка работоспособности сервиса (Liveness/Readiness probe)
 * OpenAPI spec version: 0.1.0
 */
import type { GetPingsParams, PingRecord } from '../uptime-service.schemas.js';

import { customInstance } from '../../../axios-client.js';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getPings = () => {
  const getPings = (
    siteId: string,
    params: GetPingsParams,
    options?: SecondParameter<typeof customInstance<PingRecord[]>>,
  ) => {
    return customInstance<PingRecord[]>(
      {
        url: `http://127.0.0.1:3000/sites/${siteId}/pings`,
        method: 'GET',
        params,
      },
      options,
    );
  };
  return { getPings };
};
export type GetPingsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPings>['getPings']>>
>;
