/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Upward Uptime Service API
 * REST API сервиса мониторинга доступности сайтов (uptime) в монорепозитории Upward.
 *
 * ### Возможности сервиса:
 * - Регистрация сайтов для периодического мониторинга доступности
 * - Защита от SSRF (DNS-резолвинг, фильтрация приватных/локальных сетей и проверка по списку запрещённых IP)
 * - Фоновый параллельный опрос сайтов с записью метрик в TimescaleDB
 * - Получение списка отслеживаемых сайтов и метаданных последних проверок
 * - Проверка работоспособности сервиса (Liveness/Readiness probe)
 * OpenAPI spec version: 0.1.0
 */
/**
 * Данные для регистрации нового сайта в мониторинге
 */
export interface CreateSiteDto {
  /**
     * URL сайта для проверки (поддерживаются только http:// и https://)
     * @minLength 1
     * @maxLength 2048
     */
  site: string;
  /**
     * Идентификатор пользователя-владельца
     * @minLength 1
     * @maxLength 128
     */
  user_id: string;
}

/**
 * Результат успешного создания сайта
 */
export interface CreateSiteResponseDto {
  /** Путь, по которому должен быть доступен токен */
  challenge_path: string;
  /** Секретный токен для подтверждения владения сайтом */
  challenge_token: string;
  /** Идентификатор созданного сайта */
  id: string;
  /** Статус операции */
  status: string;
}

/**
 * Идентификатор пользователя-владельца
 */
export type UserId = string;

/**
 * DTO query-параметров для получения пингов сайта
 */
export interface GetPingsDto {
  /** Идентификатор пользователя-владельца (извлекается BFF из JWT) */
  user_id: UserId;
}

/**
 * Ответ эндпоинта проверки работоспособности сервиса
 */
export interface HealthResponseDto {
  /** Пояснительное сообщение */
  message: string;
  /** Статус состояния сервиса */
  status: string;
}

/**
 * Идентификатор сайта
 */
export type SiteId = string;

/**
 * Запись замера доступности, подготовленная для сохранения в базу данных
 */
export interface PingRecord {
  duration_ms: number;
  extra: unknown;
  site_id: SiteId;
}

/**
 * Информация о сайте и статусе его последней проверки (API Response Contract)
 */
export interface SiteResponseDto {
  /** Признак подтверждения и активности сайта */
  active: boolean;
  /** Время добавления сайта (UTC) */
  created_at: string;
  /** Дополнительные данные последней проверки (время отклика, заголовки, ошибки) */
  extra?: unknown;
  /** Идентификатор сайта */
  id: string;
  /**
     * Время последней проверки (UTC)
     * @nullable
     */
  last_check?: string | null;
  /** Текущий статус сайта в очереди (idle, processing) */
  status: string;
  /** Время обновления статуса (UTC) */
  status_updated_at: string;
  /** Отслеживаемый URL */
  url: string;
  /** Идентификатор пользователя-владельца */
  user_id: string;
}

/**
 * Статус состояния сайта в очереди мониторинга
 */
export type SiteStatus = typeof SiteStatus[keyof typeof SiteStatus];


export const SiteStatus = {
  idle: 'idle',
  processing: 'processing',
} as const;

/**
 * URL сайта
 */
export type SiteUrl = string;

/**
 * Результат подтверждения владения сайтом
 */
export interface VerifySiteResponseDto {
  /** Идентификатор подтвержденного сайта */
  id: string;
  /** Статус операции */
  status: string;
}

export type GetPingsParams = {
/**
 * Идентификатор пользователя-владельца (извлекается BFF из JWT)
 * @minLength 1
 * @maxLength 128
 */
user_id: string;
};

