/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Upward Identify Service API
 * REST API сервиса идентификации и аутентификации в монорепозитории Upward.
 *
 * ### Возможности сервиса:
 * - Аутентификация по email и паролю (Argon2id)
 * - Выпуск пар токенов Access (JWT) и Refresh
 * - Безопасная ротация Refresh токенов (Token Rotation) с хранением активных сессий в Redis
 * - Интеграция с OAuth провайдерами (Google и др.)
 * - Проверка работоспособности сервиса (Health Check)
 * OpenAPI spec version: 0.1.0
 */
/**
 * Newtype для Access JWT токена
 */
export type AccessToken = string;

/**
 * Ответ эндпоинта проверки работоспособности сервиса
 */
export interface HealthResponseDto {
  /** Пояснительное сообщение */
  message: string;
  /** Статус состояния сервиса */
  status: string;
}

/**
 * Запрос на аутентификацию по email и паролю
 */
export interface LoginByPasswordRequestDto {
  /**
   * Адрес электронной почты пользователя
   * @maxLength 320
   */
  email: string;
  /**
   * Пароль пользователя в открытом виде
   * @minLength 8
   * @maxLength 128
   */
  password: string;
}

/**
 * Newtype для Refresh токена
 */
export type RefreshToken = string;

/**
 * Успешный ответ аутентификации с парой токенов
 */
export interface LoginByPasswordResponseDto {
  /** Короткоживущий JWT токен доступа (15 минут) */
  access: AccessToken;
  /** Долгоживущий одноразовый Refresh токен для ротации (30 дней) */
  refresh: RefreshToken;
}

/**
 * Ответ с открытым криптографическим ключом для валидации токенов
 */
export interface PublicKeyResponseDto {
  /** Алгоритм цифровой подписи токенов */
  algorithm: string;
  /** Публичный ключ RSA в формате PEM (X.509 SubjectPublicKeyInfo) */
  public_key: string;
}

/**
 * Запрос на обновление пары токенов (Refresh Token Rotation)
 */
export interface RefreshRequestDto {
  /** Текущий активный Refresh токен */
  refresh: RefreshToken;
}

/**
 * Запрос на регистрацию пользователя по email и паролю
 */
export interface RegisterRequestDto {
  /**
   * Адрес электронной почты пользователя
   * @maxLength 320
   */
  email: string;
  /**
   * Пароль пользователя в открытом виде
   * @minLength 8
   * @maxLength 128
   */
  password: string;
}
