/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Upward BFF API
 * Backend-For-Frontend API для веб- и мобильных клиентов Upward: единая точка входа для авторизации и мониторинга сайтов
 * OpenAPI spec version: 0.1.0
 */

export interface CreateSiteDto {
  /**
     * URL сайта для проверки (поддерживаются протоколы http:// и https://)
     * @maxLength 2048
     */
  site: string;
}
