/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Upward BFF API
 * Backend-For-Frontend API для веб- и мобильных клиентов Upward: единая точка входа для авторизации и мониторинга сайтов
 * OpenAPI spec version: 0.1.0
 */

export interface CreateSiteResponseDto {
  /** Идентификатор созданного сайта */
  id: string;
  /** Статус операции */
  status: string;
  /** Путь, по которому должен быть доступен токен */
  challenge_path: string;
  /** Секретный токен для подтверждения владения сайтом */
  challenge_token: string;
}
