/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Upward BFF API
 * Backend-For-Frontend API для веб- и мобильных клиентов Upward: единая точка входа для авторизации и мониторинга сайтов
 * OpenAPI spec version: 0.1.0
 */
import type { PingRecordDtoExtra } from './ping-record-dto-extra';

export interface PingRecordDto {
  /** Идентификатор сайта */
  site_id: string;
  /** Длительность ответа в миллисекундах */
  duration_ms: number;
  /** Дополнительные метаданные замера */
  extra?: PingRecordDtoExtra;
}
