/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Upward BFF API
 * Backend-For-Frontend API для веб- и мобильных клиентов Upward: единая точка входа для авторизации и мониторинга сайтов
 * OpenAPI spec version: 0.1.0
 */

export interface RefreshDto {
  /**
     * Refresh токен сессии (UUID v4, опционально, если передан в HttpOnly cookie)
     * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
     */
  refresh?: string;
}
