/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Upward BFF API
 * Backend-For-Frontend API для веб- и мобильных клиентов Upward: единая точка входа для авторизации и мониторинга сайтов
 * OpenAPI spec version: 0.1.0
 */
import type { SiteResponseDtoExtra } from './site-response-dto-extra';

export interface SiteResponseDto {
  /** Идентификатор сайта */
  id: string;
  /** Идентификатор пользователя-владельца */
  user_id: string;
  /** Отслеживаемый URL */
  url: string;
  /** Признак подтверждения и активности сайта */
  active: boolean;
  /** Текущий статус сайта в очереди */
  status: string;
  /** Время добавления сайта (UTC) */
  created_at: string;
  /** Время обновления статуса (UTC) */
  status_updated_at: string;
  /** Время последней проверки (UTC) */
  last_check?: string[];
  /** Дополнительные данные последней проверки */
  extra?: SiteResponseDtoExtra;
}
