/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Upward BFF API
 * Backend-For-Frontend API для веб- и мобильных клиентов Upward: единая точка входа для авторизации и мониторинга сайтов
 * OpenAPI spec version: 0.1.0
 */

export interface VerifySiteResponseDto {
  /** Идентификатор подтвержденного сайта */
  id: string;
  /** Статус операции */
  status: string;
}
