/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Upward BFF API
 * Backend-For-Frontend API для веб- и мобильных клиентов Upward: единая точка входа для авторизации и мониторинга сайтов
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateSiteDto,
  CreateSiteResponseDto,
  PingRecordDto,
  SiteResponseDto,
  VerifySiteResponseDto
} from '../model';

import { customInstance } from '../../axios-client';
import type { ErrorType , BodyType } from '../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Регистрация нового сайта для мониторинга
 */
export const sitesControllerCreateSite = (
    createSiteDto: BodyType<CreateSiteDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<CreateSiteResponseDto>(
      {url: `/sites`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSiteDto, signal
    },
      options);
    }




export const getSitesControllerCreateSiteMutationKey = () => ['sitesControllerCreateSite'] as const;

export const getSitesControllerCreateSiteMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sitesControllerCreateSite>>, TError,SitesControllerCreateSiteMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sitesControllerCreateSite>>, TError,SitesControllerCreateSiteMutationVariables, TContext> => {

const mutationKey = getSitesControllerCreateSiteMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sitesControllerCreateSite>>, SitesControllerCreateSiteMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  sitesControllerCreateSite(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SitesControllerCreateSiteMutationResult = NonNullable<Awaited<ReturnType<typeof sitesControllerCreateSite>>>
    export type SitesControllerCreateSiteMutationBody = BodyType<CreateSiteDto>
    export type SitesControllerCreateSiteMutationError = ErrorType<void>
    export type SitesControllerCreateSiteMutationVariables = {data: BodyType<CreateSiteDto>}

    /**
 * @summary Регистрация нового сайта для мониторинга
 */
export const useSitesControllerCreateSite = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sitesControllerCreateSite>>, TError,SitesControllerCreateSiteMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sitesControllerCreateSite>>,
        TError,
        SitesControllerCreateSiteMutationVariables,
        TContext
      > => {
      return useMutation(getSitesControllerCreateSiteMutationOptions(options), queryClient);
    }
    /**
 * @summary Получить список отслеживаемых сайтов текущего пользователя
 */
export const sitesControllerGetAllSites = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<SiteResponseDto[]>(
      {url: `/sites`, method: 'GET', signal
    },
      options);
    }




export const getSitesControllerGetAllSitesQueryKey = () => {
    return [
    `/sites`
    ] as const;
    }


export const getSitesControllerGetAllSitesQueryOptions = <TData = Awaited<ReturnType<typeof sitesControllerGetAllSites>>, TError = ErrorType<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sitesControllerGetAllSites>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSitesControllerGetAllSitesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof sitesControllerGetAllSites>>> = ({ signal }) => sitesControllerGetAllSites(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sitesControllerGetAllSites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SitesControllerGetAllSitesQueryResult = NonNullable<Awaited<ReturnType<typeof sitesControllerGetAllSites>>>
export type SitesControllerGetAllSitesQueryError = ErrorType<void>


export function useSitesControllerGetAllSites<TData = Awaited<ReturnType<typeof sitesControllerGetAllSites>>, TError = ErrorType<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sitesControllerGetAllSites>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sitesControllerGetAllSites>>,
          TError,
          Awaited<ReturnType<typeof sitesControllerGetAllSites>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSitesControllerGetAllSites<TData = Awaited<ReturnType<typeof sitesControllerGetAllSites>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sitesControllerGetAllSites>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sitesControllerGetAllSites>>,
          TError,
          Awaited<ReturnType<typeof sitesControllerGetAllSites>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSitesControllerGetAllSites<TData = Awaited<ReturnType<typeof sitesControllerGetAllSites>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sitesControllerGetAllSites>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить список отслеживаемых сайтов текущего пользователя
 */

export function useSitesControllerGetAllSites<TData = Awaited<ReturnType<typeof sitesControllerGetAllSites>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sitesControllerGetAllSites>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSitesControllerGetAllSitesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Подтвердить владение сайтом через HTTP-01 Challenge
 */
export const sitesControllerVerifySite = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<VerifySiteResponseDto>(
      {url: `/sites/${id}/verify`, method: 'POST', signal
    },
      options);
    }




export const getSitesControllerVerifySiteMutationKey = () => ['sitesControllerVerifySite'] as const;

export const getSitesControllerVerifySiteMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sitesControllerVerifySite>>, TError,SitesControllerVerifySiteMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sitesControllerVerifySite>>, TError,SitesControllerVerifySiteMutationVariables, TContext> => {

const mutationKey = getSitesControllerVerifySiteMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sitesControllerVerifySite>>, SitesControllerVerifySiteMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  sitesControllerVerifySite(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SitesControllerVerifySiteMutationResult = NonNullable<Awaited<ReturnType<typeof sitesControllerVerifySite>>>

    export type SitesControllerVerifySiteMutationError = ErrorType<void>
    export type SitesControllerVerifySiteMutationVariables = {id: string}

    /**
 * @summary Подтвердить владение сайтом через HTTP-01 Challenge
 */
export const useSitesControllerVerifySite = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sitesControllerVerifySite>>, TError,SitesControllerVerifySiteMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sitesControllerVerifySite>>,
        TError,
        SitesControllerVerifySiteMutationVariables,
        TContext
      > => {
      return useMutation(getSitesControllerVerifySiteMutationOptions(options), queryClient);
    }
    /**
 * @summary История замеров доступности сайта
 */
export const sitesControllerGetPings = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<PingRecordDto[]>(
      {url: `/sites/${id}/pings`, method: 'GET', signal
    },
      options);
    }




export const getSitesControllerGetPingsQueryKey = (id: string,) => {
    return [
    `/sites/${id}/pings`
    ] as const;
    }


export const getSitesControllerGetPingsQueryOptions = <TData = Awaited<ReturnType<typeof sitesControllerGetPings>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sitesControllerGetPings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSitesControllerGetPingsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof sitesControllerGetPings>>> = ({ signal }) => sitesControllerGetPings(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sitesControllerGetPings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SitesControllerGetPingsQueryResult = NonNullable<Awaited<ReturnType<typeof sitesControllerGetPings>>>
export type SitesControllerGetPingsQueryError = ErrorType<void>


export function useSitesControllerGetPings<TData = Awaited<ReturnType<typeof sitesControllerGetPings>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sitesControllerGetPings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sitesControllerGetPings>>,
          TError,
          Awaited<ReturnType<typeof sitesControllerGetPings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSitesControllerGetPings<TData = Awaited<ReturnType<typeof sitesControllerGetPings>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sitesControllerGetPings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sitesControllerGetPings>>,
          TError,
          Awaited<ReturnType<typeof sitesControllerGetPings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSitesControllerGetPings<TData = Awaited<ReturnType<typeof sitesControllerGetPings>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sitesControllerGetPings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary История замеров доступности сайта
 */

export function useSitesControllerGetPings<TData = Awaited<ReturnType<typeof sitesControllerGetPings>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sitesControllerGetPings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSitesControllerGetPingsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






