services:
  timescaledb:
    # Используем официальный образ с поддержкой PostgreSQL 17
    image: timescale/timescaledb:latest-pg17
    container_name: uptime-timescale
    restart: always
    environment:
      POSTGRES_USER: myuser          # Имя пользователя
      POSTGRES_PASSWORD: mypassword  # Пароль
      POSTGRES_DB: uptimedb          # Название базы данных
    ports:
      - "5432:5432"                  # Проброс портов (стандартный для Postgres)
    volumes:
      - tsdata:/var/lib/postgresql/data # Сохранение данных на диске хоста

  redis:
    image: redis:7-alpine
    container_name: uptime-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  tsdata: # Именованный том для таймскейла
  redisdata: # Именованный том для Redis
