/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Upward Identify Service API
 * REST API сервиса идентификации и аутентификации в монорепозитории Upward.
 *
 * ### Возможности сервиса:
 * - Аутентификация по email и паролю (Argon2id)
 * - Выпуск пар токенов Access (JWT) и Refresh
 * - Безопасная ротация Refresh токенов (Token Rotation) с хранением активных сессий в Redis
 * - Интеграция с OAuth провайдерами (Google и др.)
 * - Проверка работоспособности сервиса (Health Check)
 * OpenAPI spec version: 0.1.0
 */
import type {
  HealthResponseDto
} from '../identify-service.schemas.js';

import { customInstance } from '../../../axios-client.js';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getHealth = () => {
/**
 * Возвращает текущее состояние доступности микросервиса.
 * Используется оркестратором (Docker, Kubernetes) для liveness и readiness проб.
 * @summary Проверка работоспособности сервиса (Health Check)
 */
const healthCheck = (

 options?: SecondParameter<typeof customInstance<HealthResponseDto>>,) => {
      return customInstance<HealthResponseDto>(
      {url: `http://127.0.0.1:3001/health`, method: 'GET'
    },
      options);
    }
  return {healthCheck}};
export type HealthCheckResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHealth>['healthCheck']>>>
